UI/Controllers/StudyController.cs
using BLL.DTO;
using BLL.Interfaces;
using BLL.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace UI.Controllers
{
    public class StudyController : Controller
    {
        private readonly IStudyService _studyService;
        private readonly IUserService _userService;
        private readonly IMarksService _marksService;
        private readonly IGroupsService _groupsService;
        private readonly ISchedulesService _schedulesService;
        private readonly IDisciplinesService _disciplinesService;
        public StudyController(IStudyService studyService, 
            IUserService userService,
            ISchedulesService schedulesService,
            IMarksService marksService, 
            IGroupsService groupsService,
            IDisciplinesService disciplinesService)
        {
            _studyService = studyService;
            _userService = userService;
            _marksService = marksService;
            _groupsService = groupsService;
            _disciplinesService = disciplinesService;
            _schedulesService = schedulesService;
        }

        [Authorize]
        [HttpGet("Study/Schedules/{id}")]
        public async Task<IActionResult> Schedule(string id)
        {
            var scheduleList = await _studyService.GetScheduleGroup(id);
            //_studyService.GenerateSchedule(new DateTime(2024, 4, 1), new DateTime(2024, 5, 31));
            return View(scheduleList);
        }

        [Authorize(Roles = "Преподаватель")]
        [HttpGet("Study/Omissions/{id}")]
        public async Task<IActionResult> Omissions(string id)
        {
            var user = await _userService.GetUserInfo(id);
            var schedulesForWorker = _studyService.GetSchedulesForWorker(user.Workers.Id);
            return View(schedulesForWorker);
        }

        [HttpGet]
        public async Task<IActionResult> GetGroupMembersAndDates(int groupId, int scheduleId)
        {

            var groupMembers = await _studyService.StudentWithUsers(groupId);
            var availableDates = _studyService.GetPairDatesForSchedule(scheduleId);
            // Возврат данных в формате JSON
            return Json(new { groupMembers = groupMembers, availableDates = availableDates });
        }

        [Authorize(Roles = "Преподаватель")]
        [HttpGet("Study/Details/")]
        public async Task<IActionResult> Details(int groupId, int scheduleId)
        {
            var groupMembers = await _studyService.StudentWithUsers(groupId);
            var availableDates = _studyService.GetPairDatesForSchedule(scheduleId);
            var group = _groupsService.Get(groupId);
            var schedules = _schedulesService.Get(scheduleId);
            schedules.Disciplines = _disciplinesService.Get(schedules.DisciplinesId);
            ViewBag.AvailableDates = availableDates;  
            ViewBag.Group = group;
            ViewBag.Schedules = schedules;
            return View(groupMembers);
        }

        [Authorize(Roles = "Преподаватель")]
        [HttpPost]
        public IActionResult SaveMarks([FromBody] MarksViewModel mark)
        {
            var existingMark = _marksService.GetMarkByStudentIdAndPairId(mark.StudentId, mark.PairId);
            if (existingMark != null)           
                _marksService.Delete(existingMark.Id);  
            if(mark.Grade != -1)
            {
                var markEntity = new MarksDTO
                {
                    MarksCount = mark.Grade,
                    StudentId = mark.StudentId,
                    PairsId = mark.PairId
                };
                _marksService.Create(markEntity);
            }          
            return Ok();
        }

        [Authorize]
        [HttpGet("/Study/GetMark")]
        public IActionResult GetMark(int studentId, int pairId)
        {
            var mark = _marksService.GetMarkByStudentIdAndPairId(studentId, pairId);

            if (mark != null)
            {
                // Если оценка найдена, возвращаем ее в формате JSON
                return Json(new { MarksCount = mark.MarksCount });
            }
            else
            {
                // Если оценка не найдена, возвращаем пустой результат
                return Json(null);
            }
        }

        [Authorize]
        [HttpGet("Study/Grade/{id}")]
        public async Task<IActionResult> Grade(string id)
        {
            var student = await _userService.GetUserInfo(id);
            var groupSchedules = await _studyService.GetSchedulesForGroup(student.Groups.Id);

            ViewBag.Student = student;

            return View(groupSchedules);
        }

        [Authorize]
        [HttpGet("Study/DetailsForStudent/")]
        public IActionResult DetailsForStudent(int groupId, int scheduleId, int studentId)
        {
            var availableDates = _studyService.GetPairDatesForSchedule(scheduleId);           
            return Json(new { AvailableDates = availableDates });
        }

        [Authorize(Roles = "Заместитель кафедры")]
        [HttpGet("Study/Groups/{id}")]
        public async Task<IActionResult> Groups(string id)
        {
            var viceDepartment = await _userService.GetUserInfo(id);
            var allGroups = _studyService.GetGroupsOnDepartments(viceDepartment.Departments.Id);
            return View(allGroups);
        }
        [Authorize(Roles = "Заместитель кафедры")]
        [HttpGet("Study/GroupsStat/{id}")]
        public async Task<IActionResult> GroupsStat(string id)
        {
            var viceDepartment = await _userService.GetUserInfo(id);
            var allGroups = _studyService.GetGroupsOnDepartments(viceDepartment.Departments.Id);
            return View(allGroups);
        }

        [Authorize]
        [HttpGet("Study/GroupsSchedule")]
        public async Task<IActionResult> GroupsSchedule(int groupId)
        {           
            var groupSchedules = await _studyService.GetSchedulesForGroup(groupId);         
            return View(groupSchedules);
        }

        [HttpGet("Study/GetDetails")]
        public async Task<IActionResult> GetDetails(int groupId, int scheduleId)
        {
            // Получаем результаты запроса через ваш сервис
            var model = await _studyService.GetStudentStatistics(groupId, scheduleId);

            // Возвращаем частичное представление для отображения в модальном окне
            return Json(model);
        }
    }
}

UI/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using BLL.Interfaces;
using Microsoft.AspNetCore.Authorization;
using BLL.ViewModel;
using Microsoft.AspNetCore.Identity;
using BLL.DTO;
using DAL.Models;
using Newtonsoft.Json;
using System.Text.RegularExpressions;
using System.Text;

namespace UI.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IStudyService _studyService;
        private readonly IStudentsService _studentsService;
        private readonly HttpClient _httpClient;

        public UserController(IUserService userService, IStudyService studyService, IStudentsService studentsService)
        {
            _userService = userService;
            _studyService = studyService;
            _studentsService = studentsService;
            _httpClient = HttpClientFactory.Create();
        }

        [AllowAnonymous]
        [HttpPost("/User/Login")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LoginUser(string userName, string password)
        {
            var user = await _userService.LoginUser(userName, password);
            if (user != null)
            {

                return Ok();
            }
            else
            {
                return BadRequest("Не правильный логин или пароль");
            }
        }

        [Authorize]
        [HttpGet("/User/Profile/{id}")]
        public async Task<IActionResult> Profile(string id)
        {
            var userDTO = await _userService.GetUserInfo(id);
            return View(userDTO);
        }

        [Authorize]
        [HttpGet("/User/Logout")]
        public async Task<IActionResult> Logout()
        {
            try
            {
                await _userService.LogoutUser();
            }
            catch { }
            return RedirectToAction("Login", "Home");
        }

        [Authorize(Roles = "Заместитель кафедры")]
        public async Task<IActionResult> Students()
        {
            return View();
        }

        [Authorize(Roles = "Заместитель кафедры")]
        [HttpGet("/User/GetUsers")]
        public async Task<IActionResult> GetStudents([FromQuery] int groupId)
        {
            // Выполняем GET-запрос к API
            HttpResponseMessage response = await _httpClient.GetAsync($"api/StudentsControllers/groups/{groupId}");

            if (response.IsSuccessStatusCode)
            {
                // Читаем содержимое ответа как строку JSON
                string json = await response.Content.ReadAsStringAsync();

                // Десериализуем JSON в список студентов (предположим, что у вас есть класс Student)
                var students = JsonConvert.DeserializeObject<List<StudentWithUser>>(json);

                // Возвращаем список студентов как результат метода
                return Ok(students);
            }
            else
            {
                // В случае ошибки возвращаем статус ошибки и сообщение
                return StatusCode((int)response.StatusCode, response.ReasonPhrase);
            }
        }

        [Authorize(Roles = "Заместитель кафедры")]
        [HttpPost("/User/EditStudent")]
        public async Task<IActionResult> EditStudents([FromBody] StudentWithUser model)
        {
            if (ModelState.IsValid)
            {
                return Ok();
            }
            else
            {
                return BadRequest(ModelState);
            }
        }

        [HttpPost("/User/Add")]       
        public async Task<IActionResult> AddUser([FromBody] StudentsCrud model)
        {
            string url = $"https://localhost:7226/api/StudentsControllers/Add";

            // Выполняем HTTP PUT запрос
            HttpResponseMessage response = await _httpClient.PostAsync(url, new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json"));

            // Проверяем статус ответа
            if (response.IsSuccessStatusCode)
            {
                return Ok(); // Возвращаем успешный результат
            }
            else
            {
                // В случае ошибки возвращаем статус ошибки и сообщение
                return StatusCode((int)response.StatusCode, response.ReasonPhrase);
            }
        }

        [HttpPut("User/Update/{id}")]
        public async Task<IActionResult> UpdateUser(string id, [FromBody] StudentsEdit model)
        {
            string url = $"https://localhost:7226/api/StudentsControllers/Update/{id}";

            // Выполняем HTTP PUT запрос
            HttpResponseMessage response = await _httpClient.PutAsync(url, new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json"));

            // Проверяем статус ответа
            if (response.IsSuccessStatusCode)
            {
                return Ok(); // Возвращаем успешный результат
            }
            else
            {
                // В случае ошибки возвращаем статус ошибки и сообщение
                return StatusCode((int)response.StatusCode, response.ReasonPhrase);
            }
        }

        [HttpDelete("User/Delete/{id}")]        
        public async Task<IActionResult> DeleteUser(string id)
        {
            HttpResponseMessage response = await _httpClient.DeleteAsync($"api/StudentsControllers/Delete/{id}");
            if (response.IsSuccessStatusCode)
            {
                return Ok();
            }
            else
            {
                // В случае ошибки возвращаем статус ошибки и сообщение
                return StatusCode((int)response.StatusCode, response.ReasonPhrase);
            }
        }
    }
}

UI/Views/Study/Details.cshtml
@using BLL.ViewModel
@using BLL.DTO
@using DAL.Models
@model List<StudentWithUser>
<style>
    /* Стили для контейнера таблицы */
    .table-container {
        max-height: 500px;
        overflow-y: auto;
    }

    /* Стили для заголовка таблицы */
    .table th {
        background-color: #f2f2f2; 
        font-weight: bold; 
          
    }

    .table thead {
        position: sticky;
        top: 0; /* Закрепляем заголовок вверху */
        background-color: #f2f2f2; /* Цвет фона заголовка */
        z-index: 1; /* Поднимаем заголовок над содержимым */
    }
    .form-select:hover {
        cursor: pointer; 
        border: 1px solid #808080
    }

</style>

<h1 class="mt-3">@ViewBag.Group.NameGroup-@ViewBag.Group.Course@ViewBag.Group.NumberGroup 
    (@ViewBag.Schedules.Disciplines.DisciplineName - @ViewBag.Schedules.TypeSchedule)</h1>
<div class="table-container mt-3">   
    <table class="table">
        <!-- Заголовок таблицы -->
        <thead>
            <tr>
                <th>Студент</th>
                @foreach (var pair in ViewBag.AvailableDates)
                {
                    <th>@pair.Date.ToShortDateString()</th>
                }
            </tr>
        </thead>
        <!-- Тело таблицы -->
        <tbody>
            @foreach (var student in Model)
            {
                <tr data-student-id="@student.StudentId">
                    <td>@student.Surname @student.Name</td>
                    @foreach (var pair in ViewBag.AvailableDates)
                    {
                        <td>
                            <select class="form-select font-weight-bold text-primary" id="grade-@student.StudentId-@pair.Id" data-student-id="@student.StudentId" data-pair-id="@pair.Id">
                                <option value="-1"></option>
                                <option value="0">Н</option>
                                @if (@ViewBag.Schedules.TypeSchedule == TypeSchedule.Практика)
                                {
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                }                               
                            </select>
                        </td>                      
                    }
                </tr>
            }
        </tbody>
    </table>
</div>


<script>
    $(document).ready(function () {
        // Обработчик изменений в селекторах оценок
        $('.table-container').on('change', 'select', function () {
            var studentId = $(this).data('student-id');
            var pairId = $(this).data('pair-id');
            var grade = $(this).val();

            // Отправка данных на сервер
            $.ajax({
                url: '/Study/SaveMarks',
                type: 'POST',
                contentType: 'application/json',
                data: JSON.stringify({ studentId: studentId, pairId: pairId, grade: grade }),
                success: function (response) {
                    // Обработка успешного сохранения
                    alert("Оценка успешно сохранена");
                },
                error: function (xhr, status, error) {
                    console.error(error);
                }
            });
        });

        // Установка оценок из базы данных
        $('select').each(function () {
            var studentId = $(this).data('student-id');
            var pairId = $(this).data('pair-id');
            var gradeSelector = $(this);

            $.ajax({
                url: '/Study/GetMark',
                type: 'GET',
                dataType: 'json',
                data: { studentId: studentId, pairId: pairId },
                success: function (data) {                  
                    if (data !== null) {
                        gradeSelector.val(data.marksCount);
                    }
                },
                error: function (xhr, status, error) {
                    console.error(error);
                }
            });
        });
    });
</script>

UI/Views/Study/Grade.cshtml
@using BLL.ViewModel
@model List<ScheduleForGroupViewModel>

<h1 class="mt-3">Успеваемость</h1>

<div class="row justify-content-end mt-3">
    <div class="col-auto">
        <input type="text" class="form-control" id="searchInput" placeholder="Поиск предметов">
    </div>
</div>

<div class="row mt-3" id="scheduleCards">
    @foreach (var schedule in Model)
    {
        <div class="col-md-4 mb-3">
            <div class="card clickable-card" data-group-id="@schedule.GroupId" data-schedule-id="@schedule.ScheduleId" data-student-id="@ViewBag.Student.Students.Id">
                <div class="card-body">
                    <h5 class="card-title">@schedule.DisciplineName</h5>
                    <p class="card-text">Преподаватель: @schedule.Surname</p>
                    <p class="card-text">Тип пары: @schedule.TypeSchedule</p>
                </div>
            </div>
        </div>
    }
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Успеваемость</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" style="max-height: 400px; overflow-y: auto;">
                <table class="table">
                    <thead id="modalTableHead">
                    </thead>
                    <tbody id="modalTableBody">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



<script>
    $(document).ready(function () {
        // Обработчик события ввода в поле поиска
        $('#searchInput').on('input', function () {
            var searchText = $(this).val().toLowerCase(); // Получаем введенный текст и приводим к нижнему регистру

            // Проходимся по каждому предмету и скрываем те, которые не соответствуют введенному тексту
            $('#scheduleCards .card').each(function () {
                var disciplineName = $(this).find('.card-title').text().toLowerCase(); // Получаем название предмета и приводим к нижнему регистру

                // Проверяем, содержит ли название предмета введенный текст
                if (disciplineName.includes(searchText)) {
                    $(this).show(); // Отображаем предмет, если он соответствует запросу
                } else {
                    $(this).hide(); // Скрываем предмет, если он не соответствует запросу
                }
            });
        });
    });


    $(document).ready(function () {
        $('.clickable-card').click(function () {
            var groupId = $(this).data('group-id');
            var scheduleId = $(this).data('schedule-id');
            var studentId = $(this).data('student-id');

            $.ajax({
                url: '/Study/DetailsForStudent/',
                type: 'GET',
                data: { groupId: groupId, scheduleId: scheduleId, studentId: studentId },
                success: function (data) {
                    $('#modalTableHead').empty();
                    $('#modalTableBody').empty();

                    var availableDates = data.availableDates;

                    // Добавляем заголовки дат в таблицу модального окна
                    var headerRow = '<tr>';
                    var bodyRow = '<tr>';
                    availableDates.forEach(function (pair) {
                        headerRow += '<th>' + formatDate(pair.date) + '</th>';
                        bodyRow += '<td data-pair-id="' + pair.id + '"></td>';
                    });
                    bodyRow += '</tr>';
                    headerRow += '</tr>';

                    $('#modalTableHead').append(headerRow);
                    $('#modalTableBody').append(bodyRow);

                    // Добавляем данные в таблицу модального окна
                    $('#modalTableBody td[data-pair-id]').each(function () {
                        var pairId = $(this).data('pair-id');
                        $.ajax({
                            url: '/Study/GetMark',
                            type: 'GET',
                            data: { studentId: studentId, pairId: pairId },
                            success: function (markData) {
                                var cellContent;
                                if (markData !== undefined && markData !== null) {
                                    if (markData.marksCount === 0)
                                        cellContent = 'Н';
                                    else
                                        cellContent = markData.marksCount;
                                } else {
                                    cellContent = '-';
                                }
                                $(this).text(cellContent);
                            }.bind(this),  // Используем bind(this), чтобы сохранить контекст this
                            error: function () {
                                $(this).text('Ошибка при получении оценки');
                            }.bind(this)  // Используем bind(this), чтобы сохранить контекст this
                        });
                    });

                    $('#exampleModal').modal('show');
                },
                error: function () {
                    alert('Ошибка при получении данных о датах пар.');
                }
            });
        });
    });

    // Функция для форматирования даты
    function formatDate(dateString) {
        var date = new Date(dateString);
        var day = ('0' + date.getDate()).slice(-2);
        var month = ('0' + (date.getMonth() + 1)).slice(-2);
        var year = date.getFullYear();
        return day + '.' + month + '.' + year;
    }

</script>

UI/Views/Study/Groups.cshtml
@using BLL.DTO
@model List<GroupsDTO>

<style>
    .card.clickable-card:hover {      
        cursor: pointer; /* Изменение курсора */
        border: solid 1px #f0f0f0
    }
</style>

<H1 class="mt-3 mb-3">Ваши группы</H1>
<div class="row mt-3" id="groupCards">
    @foreach (var schedule in Model)
    {
        <div class="col-md-4 mb-3">
            <a href="@Url.Action("Students", "User", new { groupId = schedule.Id })" class="card clickable-card">
                <div class="card-body">
                    <h5 class="card-title">@schedule.NameGroup - @schedule.Course@schedule.NumberGroup</h5>
                </div>
            </a>
        </div>
    }
</div>

UI/Views/Study/GroupsSchedule.cshtml
@using BLL.ViewModel
@model List<ScheduleForGroupViewModel>

<style>
    

</style>

<h1 class="mt-3">Успеваемость</h1>

<div class="row justify-content-end mt-3">
    <div class="col-auto">
        <input type="text" class="form-control" id="searchInput" placeholder="Поиск предметов">
    </div>
</div>

<div class="row mt-3" id="scheduleCards">
    @foreach (var schedule in Model)
    {
        <div class="col-md-4 mb-3">
            <div class="card clickable-card" data-group-id="@schedule.GroupId" data-schedule-id="@schedule.ScheduleId">
                <div class="card-body">
                    <h5 class="card-title">@schedule.DisciplineName</h5>
                    <p class="card-text">Преподаватель: @schedule.Surname</p>
                    <p class="card-text">Тип пары: @schedule.TypeSchedule</p>
                </div>
            </div>
        </div>
    }
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Результаты запроса</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" style="max-height: 70vh; overflow-y: auto;">
                <!-- Таблица для отображения данных -->
                <table class="table">
                    <thead>
                        <tr>
                            <th>Фамилия</th>
                            <th>Имя</th>
                            <th>Отчество</th>
                            <th>Средний бал</th>
                            <th>Количество пропусков</th>
                        </tr>
                    </thead>
                    <tbody id="modal-body-table">
                        <!-- Здесь будут отображаться данные -->
                    </tbody>
                </table>
            </div>
            <div>
                <strong>Общий средний балл:</strong> <span id="total-average-mark"></span><br>
                <strong>Общее количество пропусков:</strong> <span id="total-absences"></span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        // Обработчик события ввода в поле поиска
        $('#searchInput').on('input', function () {
            var searchText = $(this).val().toLowerCase(); // Получаем введенный текст и приводим к нижнему регистру

            // Проходимся по каждому предмету и скрываем те, которые не соответствуют введенному тексту
            $('#scheduleCards .card').each(function () {
                var disciplineName = $(this).find('.card-title').text().toLowerCase(); // Получаем название предмета и приводим к нижнему регистру

                // Проверяем, содержит ли название предмета введенный текст
                if (disciplineName.includes(searchText)) {
                    $(this).show(); // Отображаем предмет, если он соответствует запросу
                } else {
                    $(this).hide(); // Скрываем предмет, если он не соответствует запросу
                }
            });
        });
    });

    $(document).ready(function () {
        // При нажатии на карточку
        $('.clickable-card').click(function () {
            // Получаем идентификатор группы и расписания из атрибутов данных карточки
            var groupId = $(this).data('group-id');
            var scheduleId = $(this).data('schedule-id');

            // Выполняем AJAX-запрос к вашему контроллеру для получения результатов
            $.ajax({
                url: '/Study/GetDetails', // Замените на соответствующий URL вашего контроллера и действия
                type: 'GET',
                data: { groupId: groupId, scheduleId: scheduleId },
                success: function (data) {
                    // Показываем модальное окно
                    $('#myModal').modal('show');

                    // Обновляем содержимое модального окна с помощью данных JSON
                    $('#modal-body-table').empty();
                    var studentsWithMarks = data.filter(item => item.averageMark !== null);
                    var totalAverageMark = studentsWithMarks.reduce((acc, item) => acc + item.averageMark, 0) / studentsWithMarks.length;
                    // Рассчет общего количества пропусков
                    var totalAbsences = data.reduce((acc, item) => acc + item.absences, 0);

                    // Отображение рассчитанных значений в модальном окне
                    $('#total-average-mark').text((!isNaN(totalAverageMark) ? totalAverageMark.toFixed(2) : '-'));

                    $('#total-absences').text(totalAbsences);
                    data.forEach(function (item) {
                        var row = '<tr>';
                        row += '<td>' + item.surname + '</td>';
                        row += '<td>' + item.name + '</td>';
                        row += '<td>' + item.middleName + '</td>';
                        row += '<td>' + (item.averageMark != null ? item.averageMark : '-') + '</td>';
                        row += '<td>' + item.absences + '</td>';
                        row += '</tr>';

                        $('#modal-body-table').append(row);
                    });
                }
            });
        });
    });
</script>

UI/Views/Study/GroupsStat.cshtml
@using BLL.DTO
@model List<GroupsDTO>

<style>
    .card.clickable-card:hover {
        cursor: pointer; /* Изменение курсора */
        border: solid 1px #f0f0f0
    }
</style>

<H1 class="mt-3 mb-3">Ваши группы</H1>
<div class="row mt-3" id="groupCards">
    @foreach (var schedule in Model)
    {
        <div class="col-md-4 mb-3">
            <a href="@Url.Action("GroupsSchedule", "Study", new { groupId = schedule.Id })" class="card clickable-card">
                <div class="card-body">
                    <h5 class="card-title">@schedule.NameGroup - @schedule.Course@schedule.NumberGroup</h5>
                </div>
            </a>
        </div>
    }
</div>

UI/Views/Study/Omissions.cshtml
@using BLL.ViewModel
@model List<SchedulesForTeacher>

<style>
    /* Стили для изменения курсора при наведении на строку */
    .clickable-row:hover {
        cursor: pointer;
        background-color: #808080; /* Изменение цвета фона при наведении */
        border: 2px solid #808080
    }
</style>

<h1 class="mt-3">Ваши Журналы</h1>

<table class="table mt-3">
    <thead>
        <tr>
            <th>Группа</th>
            <th>Дисциплина</th>
            <th>Тип пары</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var schedule in Model)
        {
            <tr class="clickable-row" data-group-id="@schedule.GroupId" data-schedule-id="@schedule.ScheduleId">
                <td>@schedule.GroupName - @schedule.Course@schedule.GroupNumber</td>
                <td>@schedule.DisciplineName</td>
                <td>@schedule.TypeSchedule</td>
            </tr>
        }
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('.clickable-row').click(function () {
            var groupId = $(this).data('group-id');
            var scheduleId = $(this).data('schedule-id');
            window.location.href = '/Study/Details?groupId=' + groupId + '&scheduleId=' + scheduleId;
        });
    });
</script>